// source: base.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.base.proto.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Timestamp');

goog.forwardDeclare('proto.base.proto.Event');
goog.forwardDeclare('proto.base.proto.Type');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.base.proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.base.proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.base.proto.Message.displayName = 'proto.base.proto.Message';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.base.proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.base.proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.base.proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.base.proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: msg.getData_asB64(),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    seq: (f = msg.getSeq()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    from: jspb.Message.getFieldWithDefault(msg, 6, ""),
    to: jspb.Message.getFieldWithDefault(msg, 7, ""),
    event: jspb.Message.getFieldWithDefault(msg, 8, 0),
    queue: jspb.Message.getBooleanFieldWithDefault(msg, 9, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.base.proto.Message}
 */
proto.base.proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.base.proto.Message;
  return proto.base.proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.base.proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.base.proto.Message}
 */
proto.base.proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 2:
      var value = /** @type {!proto.base.proto.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setSeq(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTo(value);
      break;
    case 8:
      var value = /** @type {!proto.base.proto.Event} */ (reader.readEnum());
      msg.setEvent(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setQueue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.base.proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.base.proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.base.proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.base.proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSeq();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTo();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEvent();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getQueue();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
};


/**
 * optional bytes data = 1;
 * @return {string}
 */
proto.base.proto.Message.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes data = 1;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.base.proto.Message.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.base.proto.Message.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional Type type = 2;
 * @return {!proto.base.proto.Type}
 */
proto.base.proto.Message.prototype.getType = function() {
  return /** @type {!proto.base.proto.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.base.proto.Type} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp seq = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.base.proto.Message.prototype.getSeq = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.base.proto.Message} returns this
*/
proto.base.proto.Message.prototype.setSeq = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.clearSeq = function() {
  return this.setSeq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.base.proto.Message.prototype.hasSeq = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string from = 6;
 * @return {string}
 */
proto.base.proto.Message.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string to = 7;
 * @return {string}
 */
proto.base.proto.Message.prototype.getTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setTo = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Event event = 8;
 * @return {!proto.base.proto.Event}
 */
proto.base.proto.Message.prototype.getEvent = function() {
  return /** @type {!proto.base.proto.Event} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.base.proto.Event} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setEvent = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional bool queue = 9;
 * @return {boolean}
 */
proto.base.proto.Message.prototype.getQueue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.base.proto.Message} returns this
 */
proto.base.proto.Message.prototype.setQueue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


